DROP TABLE IF EXISTS users, events, categories, locations;

CREATE TABLE IF NOT EXISTS users(
id INTEGER GENERATED ALWAYS AS IDENTITY,
name VARCHAR(250) NOT NULL,
email VARCHAR(254) NOT NULL,
CONSTRAINT user_id PRIMARY KEY(id),
CONSTRAINT user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories(
id	INTEGER GENERATED ALWAYS AS IDENTITY,
name VARCHAR(50) NOT NULL,
CONSTRAINT category_id PRIMARY KEY(id),
CONSTRAINT category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations(
id INTEGER GENERATED ALWAYS AS IDENTITY,
lat REAL NOT NULL,
lon REAL NOT NULL,
CONSTRAINT location_id PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS events(
id INTEGER GENERATED ALWAYS AS IDENTITY,
annotation VARCHAR(2000),
category_id INTEGER REFERENCES categories(id),
description VARCHAR(7000),
eventDate TIMESTAMP WITHOUT TIME ZONE,
location_id INTEGER REFERENCES locations(id),
paid BOOLEAN,
participantLimit INTEGER,
requestModeration BOOLEAN,
title VARCHAR(120),
CONSTRAINT events_id PRIMARY KEY(id)
);